title: Jenni Peltola â€“ Portfolio
description: Software developer student | Fullstack & Android projects
theme: jekyll-theme-cayman

markdown: kramdown

show_downloads: false

github:
  is_project_page: true
